theme: jekyll-theme-slate
title: Captivate Automation Courses
description: This is a WIP, the purpose of this script is to automate the creation of a course UI inside CP, 
using a standard for panel, navigation buttons, sound on off, text position (dependind the position of the image), 
image styles, list, tables, h1, font and all styles, the idea behind this is to present the texts to the user using the
Slide Notes imported thru the the accessibility panel and there only use HTML formatting texts.
Here are the steps to use the script:<br>
